// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"

	"github.com/google/uuid"
)

type Study struct {
	ID             uuid.UUID
	StudyID        string
	Patient        string
	Age            int
	Department     string
	NameOperation  string
	DescrOperation string
	TimeBeginning  time.Time
	TimeDuration   int
	Surgeon        string
	DicomLink      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
