// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirp.sql

package db

import (
	"context"
)

const getStudies = `-- name: GetStudies :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, descr_operation, time_beginning, time_duration, surgeon, dicom_link FROM studies
ORDER BY created_at ASC
`

func (q *Queries) GetStudies(ctx context.Context) ([]Study, error) {
	rows, err := q.db.QueryContext(ctx, getStudies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
