// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_records.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgentRecord = `-- name: CreateAgentRecord :exec
INSERT INTO agent_records (agent_id, status)
VALUES ($1, $2)
`

type CreateAgentRecordParams struct {
	AgentID int32  `json:"agent_id"`
	Status  string `json:"status"`
}

func (q *Queries) CreateAgentRecord(ctx context.Context, arg CreateAgentRecordParams) error {
	_, err := q.exec(ctx, q.createAgentRecordStmt, createAgentRecord, arg.AgentID, arg.Status)
	return err
}

const deleteAgentRecordsByAgentID = `-- name: DeleteAgentRecordsByAgentID :exec
DELETE FROM agent_records
WHERE agent_id = $1
`

func (q *Queries) DeleteAgentRecordsByAgentID(ctx context.Context, agentID int32) error {
	_, err := q.exec(ctx, q.deleteAgentRecordsByAgentIDStmt, deleteAgentRecordsByAgentID, agentID)
	return err
}

const getAgentRecordsByAgentID = `-- name: GetAgentRecordsByAgentID :many
SELECT sent_at FROM agent_records
WHERE agent_id = $1
ORDER BY sent_at DESC
`

func (q *Queries) GetAgentRecordsByAgentID(ctx context.Context, agentID int32) ([]time.Time, error) {
	rows, err := q.query(ctx, q.getAgentRecordsByAgentIDStmt, getAgentRecordsByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var sent_at time.Time
		if err := rows.Scan(&sent_at); err != nil {
			return nil, err
		}
		items = append(items, sent_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentRecordsByAgentIDandStatus = `-- name: GetAgentRecordsByAgentIDandStatus :many
SELECT sent_at FROM agent_records
WHERE agent_id = $1 AND status = $2
ORDER BY sent_at DESC
`

type GetAgentRecordsByAgentIDandStatusParams struct {
	AgentID int32  `json:"agent_id"`
	Status  string `json:"status"`
}

func (q *Queries) GetAgentRecordsByAgentIDandStatus(ctx context.Context, arg GetAgentRecordsByAgentIDandStatusParams) ([]time.Time, error) {
	rows, err := q.query(ctx, q.getAgentRecordsByAgentIDandStatusStmt, getAgentRecordsByAgentIDandStatus, arg.AgentID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []time.Time
	for rows.Next() {
		var sent_at time.Time
		if err := rows.Scan(&sent_at); err != nil {
			return nil, err
		}
		items = append(items, sent_at)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentRecordsByStatus = `-- name: GetAgentRecordsByStatus :many
SELECT id FROM agent_records
WHERE status = $1
ORDER BY sent_at DESC
`

func (q *Queries) GetAgentRecordsByStatus(ctx context.Context, status string) ([]uuid.UUID, error) {
	rows, err := q.query(ctx, q.getAgentRecordsByStatusStmt, getAgentRecordsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
