// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAgentRecordStmt, err = db.PrepareContext(ctx, createAgentRecord); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgentRecord: %w", err)
	}
	if q.createStudyStmt, err = db.PrepareContext(ctx, createStudy); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStudy: %w", err)
	}
	if q.deleteAgentRecordsByAgentIDStmt, err = db.PrepareContext(ctx, deleteAgentRecordsByAgentID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAgentRecordsByAgentID: %w", err)
	}
	if q.getAgentRecordsByAgentIDStmt, err = db.PrepareContext(ctx, getAgentRecordsByAgentID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgentRecordsByAgentID: %w", err)
	}
	if q.getAgentRecordsByAgentIDandStatusStmt, err = db.PrepareContext(ctx, getAgentRecordsByAgentIDandStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgentRecordsByAgentIDandStatus: %w", err)
	}
	if q.getAgentRecordsByStatusStmt, err = db.PrepareContext(ctx, getAgentRecordsByStatus); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgentRecordsByStatus: %w", err)
	}
	if q.getStudiesStmt, err = db.PrepareContext(ctx, getStudies); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudies: %w", err)
	}
	if q.getStudiesByDateStmt, err = db.PrepareContext(ctx, getStudiesByDate); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesByDate: %w", err)
	}
	if q.getStudiesByDateAndStudyTypeStmt, err = db.PrepareContext(ctx, getStudiesByDateAndStudyType); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesByDateAndStudyType: %w", err)
	}
	if q.getStudiesByDateAndSurgeonStmt, err = db.PrepareContext(ctx, getStudiesByDateAndSurgeon); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesByDateAndSurgeon: %w", err)
	}
	if q.getStudiesByDateSurgeonStudyTypeStmt, err = db.PrepareContext(ctx, getStudiesByDateSurgeonStudyType); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesByDateSurgeonStudyType: %w", err)
	}
	if q.getStudiesByStudyTypeStmt, err = db.PrepareContext(ctx, getStudiesByStudyType); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesByStudyType: %w", err)
	}
	if q.getStudiesBySurgeonStmt, err = db.PrepareContext(ctx, getStudiesBySurgeon); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesBySurgeon: %w", err)
	}
	if q.getStudiesBySurgeonAndStudyTypeStmt, err = db.PrepareContext(ctx, getStudiesBySurgeonAndStudyType); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudiesBySurgeonAndStudyType: %w", err)
	}
	if q.getStudyByIDStmt, err = db.PrepareContext(ctx, getStudyByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudyByID: %w", err)
	}
	if q.getStudyByPatientStmt, err = db.PrepareContext(ctx, getStudyByPatient); err != nil {
		return nil, fmt.Errorf("error preparing query GetStudyByPatient: %w", err)
	}
	if q.softDeleteAllStudiesStmt, err = db.PrepareContext(ctx, softDeleteAllStudies); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteAllStudies: %w", err)
	}
	if q.softDeleteStudyStmt, err = db.PrepareContext(ctx, softDeleteStudy); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteStudy: %w", err)
	}
	if q.updateStudyDicomLinkStmt, err = db.PrepareContext(ctx, updateStudyDicomLink); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStudyDicomLink: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAgentRecordStmt != nil {
		if cerr := q.createAgentRecordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgentRecordStmt: %w", cerr)
		}
	}
	if q.createStudyStmt != nil {
		if cerr := q.createStudyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStudyStmt: %w", cerr)
		}
	}
	if q.deleteAgentRecordsByAgentIDStmt != nil {
		if cerr := q.deleteAgentRecordsByAgentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAgentRecordsByAgentIDStmt: %w", cerr)
		}
	}
	if q.getAgentRecordsByAgentIDStmt != nil {
		if cerr := q.getAgentRecordsByAgentIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentRecordsByAgentIDStmt: %w", cerr)
		}
	}
	if q.getAgentRecordsByAgentIDandStatusStmt != nil {
		if cerr := q.getAgentRecordsByAgentIDandStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentRecordsByAgentIDandStatusStmt: %w", cerr)
		}
	}
	if q.getAgentRecordsByStatusStmt != nil {
		if cerr := q.getAgentRecordsByStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentRecordsByStatusStmt: %w", cerr)
		}
	}
	if q.getStudiesStmt != nil {
		if cerr := q.getStudiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesStmt: %w", cerr)
		}
	}
	if q.getStudiesByDateStmt != nil {
		if cerr := q.getStudiesByDateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesByDateStmt: %w", cerr)
		}
	}
	if q.getStudiesByDateAndStudyTypeStmt != nil {
		if cerr := q.getStudiesByDateAndStudyTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesByDateAndStudyTypeStmt: %w", cerr)
		}
	}
	if q.getStudiesByDateAndSurgeonStmt != nil {
		if cerr := q.getStudiesByDateAndSurgeonStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesByDateAndSurgeonStmt: %w", cerr)
		}
	}
	if q.getStudiesByDateSurgeonStudyTypeStmt != nil {
		if cerr := q.getStudiesByDateSurgeonStudyTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesByDateSurgeonStudyTypeStmt: %w", cerr)
		}
	}
	if q.getStudiesByStudyTypeStmt != nil {
		if cerr := q.getStudiesByStudyTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesByStudyTypeStmt: %w", cerr)
		}
	}
	if q.getStudiesBySurgeonStmt != nil {
		if cerr := q.getStudiesBySurgeonStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesBySurgeonStmt: %w", cerr)
		}
	}
	if q.getStudiesBySurgeonAndStudyTypeStmt != nil {
		if cerr := q.getStudiesBySurgeonAndStudyTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudiesBySurgeonAndStudyTypeStmt: %w", cerr)
		}
	}
	if q.getStudyByIDStmt != nil {
		if cerr := q.getStudyByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudyByIDStmt: %w", cerr)
		}
	}
	if q.getStudyByPatientStmt != nil {
		if cerr := q.getStudyByPatientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStudyByPatientStmt: %w", cerr)
		}
	}
	if q.softDeleteAllStudiesStmt != nil {
		if cerr := q.softDeleteAllStudiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteAllStudiesStmt: %w", cerr)
		}
	}
	if q.softDeleteStudyStmt != nil {
		if cerr := q.softDeleteStudyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteStudyStmt: %w", cerr)
		}
	}
	if q.updateStudyDicomLinkStmt != nil {
		if cerr := q.updateStudyDicomLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStudyDicomLinkStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                    DBTX
	tx                                    *sql.Tx
	createAgentRecordStmt                 *sql.Stmt
	createStudyStmt                       *sql.Stmt
	deleteAgentRecordsByAgentIDStmt       *sql.Stmt
	getAgentRecordsByAgentIDStmt          *sql.Stmt
	getAgentRecordsByAgentIDandStatusStmt *sql.Stmt
	getAgentRecordsByStatusStmt           *sql.Stmt
	getStudiesStmt                        *sql.Stmt
	getStudiesByDateStmt                  *sql.Stmt
	getStudiesByDateAndStudyTypeStmt      *sql.Stmt
	getStudiesByDateAndSurgeonStmt        *sql.Stmt
	getStudiesByDateSurgeonStudyTypeStmt  *sql.Stmt
	getStudiesByStudyTypeStmt             *sql.Stmt
	getStudiesBySurgeonStmt               *sql.Stmt
	getStudiesBySurgeonAndStudyTypeStmt   *sql.Stmt
	getStudyByIDStmt                      *sql.Stmt
	getStudyByPatientStmt                 *sql.Stmt
	softDeleteAllStudiesStmt              *sql.Stmt
	softDeleteStudyStmt                   *sql.Stmt
	updateStudyDicomLinkStmt              *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                    tx,
		tx:                                    tx,
		createAgentRecordStmt:                 q.createAgentRecordStmt,
		createStudyStmt:                       q.createStudyStmt,
		deleteAgentRecordsByAgentIDStmt:       q.deleteAgentRecordsByAgentIDStmt,
		getAgentRecordsByAgentIDStmt:          q.getAgentRecordsByAgentIDStmt,
		getAgentRecordsByAgentIDandStatusStmt: q.getAgentRecordsByAgentIDandStatusStmt,
		getAgentRecordsByStatusStmt:           q.getAgentRecordsByStatusStmt,
		getStudiesStmt:                        q.getStudiesStmt,
		getStudiesByDateStmt:                  q.getStudiesByDateStmt,
		getStudiesByDateAndStudyTypeStmt:      q.getStudiesByDateAndStudyTypeStmt,
		getStudiesByDateAndSurgeonStmt:        q.getStudiesByDateAndSurgeonStmt,
		getStudiesByDateSurgeonStudyTypeStmt:  q.getStudiesByDateSurgeonStudyTypeStmt,
		getStudiesByStudyTypeStmt:             q.getStudiesByStudyTypeStmt,
		getStudiesBySurgeonStmt:               q.getStudiesBySurgeonStmt,
		getStudiesBySurgeonAndStudyTypeStmt:   q.getStudiesBySurgeonAndStudyTypeStmt,
		getStudyByIDStmt:                      q.getStudyByIDStmt,
		getStudyByPatientStmt:                 q.getStudyByPatientStmt,
		softDeleteAllStudiesStmt:              q.softDeleteAllStudiesStmt,
		softDeleteStudyStmt:                   q.softDeleteStudyStmt,
		updateStudyDicomLinkStmt:              q.updateStudyDicomLinkStmt,
	}
}
