// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Study struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	StudyID        string         `json:"study_id"`
	Patient        string         `json:"patient"`
	Age            sql.NullInt32  `json:"age"`
	Department     string         `json:"department"`
	NameOperation  string         `json:"name_operation"`
	StudyType      string         `json:"study_type"`
	DescrOperation string         `json:"descr_operation"`
	TimeBeginning  sql.NullTime   `json:"time_beginning"`
	TimeDuration   sql.NullInt32  `json:"time_duration"`
	Surgeon        string         `json:"surgeon"`
	DicomLink      sql.NullString `json:"dicom_link"`
	Deleted        bool           `json:"deleted"`
}
