// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AgentRecord struct {
	ID      uuid.UUID `json:"id"`
	AgentID int32     `json:"agent_id"`
	Status  string    `json:"status"`
	SentAt  time.Time `json:"sent_at"`
}

type Study struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	StudyID        string         `json:"study_id"`
	Patient        string         `json:"patient"`
	Age            sql.NullInt32  `json:"age"`
	Department     string         `json:"department"`
	NameOperation  string         `json:"name_operation"`
	StudyType      string         `json:"study_type"`
	DescrOperation string         `json:"descr_operation"`
	TimeBeginning  sql.NullTime   `json:"time_beginning"`
	TimeDuration   sql.NullInt32  `json:"time_duration"`
	Surgeon        string         `json:"surgeon"`
	DicomLink      sql.NullString `json:"dicom_link"`
	Deleted        bool           `json:"deleted"`
}

type UserRequest struct {
	ID          uuid.UUID      `json:"id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Status      string         `json:"status"`
	UserID      string         `json:"user_id"`
	RequestType string         `json:"request_type"`
	Command     sql.NullString `json:"command"`
	StudyID     sql.NullString `json:"study_id"`
	XaID        sql.NullString `json:"xa_id"`
	CtID        sql.NullString `json:"ct_id"`
	StudyFilter sql.NullString `json:"study_filter"`
	XaFilter    sql.NullString `json:"xa_filter"`
	CtFilter    sql.NullString `json:"ct_filter"`
	ErrorLog    sql.NullString `json:"error_log"`
}
