// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AgentRecord struct {
	ID      uuid.UUID `json:"id"`
	AgentID int32     `json:"agent_id"`
	Status  string    `json:"status"`
	SentAt  time.Time `json:"sent_at"`
}

type Study struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	StudyID        string         `json:"study_id"`
	Patient        string         `json:"patient"`
	Age            sql.NullInt32  `json:"age"`
	Department     string         `json:"department"`
	NameOperation  string         `json:"name_operation"`
	StudyType      string         `json:"study_type"`
	DescrOperation string         `json:"descr_operation"`
	Recommendation string         `json:"recommendation"`
	TimeBeginning  sql.NullTime   `json:"time_beginning"`
	TimeDuration   sql.NullInt32  `json:"time_duration"`
	Surgeon        string         `json:"surgeon"`
	DicomLink      sql.NullString `json:"dicom_link"`
	Deleted        bool           `json:"deleted"`
}

type UserRequest struct {
	ID             uuid.UUID       `json:"id"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	AvailableAt    time.Time       `json:"available_at"`
	LeaseExpiresAt sql.NullTime    `json:"lease_expires_at"`
	CompletedAt    sql.NullTime    `json:"completed_at"`
	Status         string          `json:"status"`
	UserID         string          `json:"user_id"`
	AgentID        int32           `json:"agent_id"`
	RequestType    string          `json:"request_type"`
	Command        string          `json:"command"`
	Payload        json.RawMessage `json:"payload"`
	Result         json.RawMessage `json:"result"`
	ErrorLog       sql.NullString  `json:"error_log"`
	AttemptCount   int32           `json:"attempt_count"`
	MaxAttempts    int32           `json:"max_attempts"`
}
