// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: studies.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStudy = `-- name: CreateStudy :one
INSERT INTO studies (study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted
`

type CreateStudyParams struct {
	StudyID        string         `json:"study_id"`
	Patient        string         `json:"patient"`
	Age            sql.NullInt32  `json:"age"`
	Department     string         `json:"department"`
	NameOperation  string         `json:"name_operation"`
	StudyType      string         `json:"study_type"`
	DescrOperation string         `json:"descr_operation"`
	TimeBeginning  sql.NullTime   `json:"time_beginning"`
	TimeDuration   sql.NullInt32  `json:"time_duration"`
	Surgeon        string         `json:"surgeon"`
	DicomLink      sql.NullString `json:"dicom_link"`
}

func (q *Queries) CreateStudy(ctx context.Context, arg CreateStudyParams) (Study, error) {
	row := q.queryRow(ctx, q.createStudyStmt, createStudy,
		arg.StudyID,
		arg.Patient,
		arg.Age,
		arg.Department,
		arg.NameOperation,
		arg.StudyType,
		arg.DescrOperation,
		arg.TimeBeginning,
		arg.TimeDuration,
		arg.Surgeon,
		arg.DicomLink,
	)
	var i Study
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudyID,
		&i.Patient,
		&i.Age,
		&i.Department,
		&i.NameOperation,
		&i.StudyType,
		&i.DescrOperation,
		&i.TimeBeginning,
		&i.TimeDuration,
		&i.Surgeon,
		&i.DicomLink,
		&i.Deleted,
	)
	return i, err
}

const getStudies = `-- name: GetStudies :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE deleted = false
ORDER BY created_at ASC
`

func (q *Queries) GetStudies(ctx context.Context) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesStmt, getStudies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesByDate = `-- name: GetStudiesByDate :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE time_beginning::date = $1 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

func (q *Queries) GetStudiesByDate(ctx context.Context, timeBeginning sql.NullTime) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesByDateStmt, getStudiesByDate, timeBeginning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesByDateAndStudyType = `-- name: GetStudiesByDateAndStudyType :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE time_beginning::date = $1 AND study_type = $2 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

type GetStudiesByDateAndStudyTypeParams struct {
	TimeBeginning sql.NullTime `json:"time_beginning"`
	StudyType     string       `json:"study_type"`
}

func (q *Queries) GetStudiesByDateAndStudyType(ctx context.Context, arg GetStudiesByDateAndStudyTypeParams) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesByDateAndStudyTypeStmt, getStudiesByDateAndStudyType, arg.TimeBeginning, arg.StudyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesByDateAndSurgeon = `-- name: GetStudiesByDateAndSurgeon :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE time_beginning::date = $1 AND surgeon = $2 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

type GetStudiesByDateAndSurgeonParams struct {
	TimeBeginning sql.NullTime `json:"time_beginning"`
	Surgeon       string       `json:"surgeon"`
}

func (q *Queries) GetStudiesByDateAndSurgeon(ctx context.Context, arg GetStudiesByDateAndSurgeonParams) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesByDateAndSurgeonStmt, getStudiesByDateAndSurgeon, arg.TimeBeginning, arg.Surgeon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesByDateSurgeonStudyType = `-- name: GetStudiesByDateSurgeonStudyType :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE time_beginning::date = $1 AND surgeon = $2 AND study_type = $3 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

type GetStudiesByDateSurgeonStudyTypeParams struct {
	TimeBeginning sql.NullTime `json:"time_beginning"`
	Surgeon       string       `json:"surgeon"`
	StudyType     string       `json:"study_type"`
}

func (q *Queries) GetStudiesByDateSurgeonStudyType(ctx context.Context, arg GetStudiesByDateSurgeonStudyTypeParams) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesByDateSurgeonStudyTypeStmt, getStudiesByDateSurgeonStudyType, arg.TimeBeginning, arg.Surgeon, arg.StudyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesByStudyType = `-- name: GetStudiesByStudyType :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE study_type = $1 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

func (q *Queries) GetStudiesByStudyType(ctx context.Context, studyType string) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesByStudyTypeStmt, getStudiesByStudyType, studyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesBySurgeon = `-- name: GetStudiesBySurgeon :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE surgeon = $1 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

func (q *Queries) GetStudiesBySurgeon(ctx context.Context, surgeon string) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesBySurgeonStmt, getStudiesBySurgeon, surgeon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudiesBySurgeonAndStudyType = `-- name: GetStudiesBySurgeonAndStudyType :many
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE surgeon = $1 AND study_type = $2 AND deleted = false
ORDER BY time_beginning DESC, created_at DESC
`

type GetStudiesBySurgeonAndStudyTypeParams struct {
	Surgeon   string `json:"surgeon"`
	StudyType string `json:"study_type"`
}

func (q *Queries) GetStudiesBySurgeonAndStudyType(ctx context.Context, arg GetStudiesBySurgeonAndStudyTypeParams) ([]Study, error) {
	rows, err := q.query(ctx, q.getStudiesBySurgeonAndStudyTypeStmt, getStudiesBySurgeonAndStudyType, arg.Surgeon, arg.StudyType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Study
	for rows.Next() {
		var i Study
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudyID,
			&i.Patient,
			&i.Age,
			&i.Department,
			&i.NameOperation,
			&i.StudyType,
			&i.DescrOperation,
			&i.TimeBeginning,
			&i.TimeDuration,
			&i.Surgeon,
			&i.DicomLink,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudyByID = `-- name: GetStudyByID :one
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE id = $1 AND deleted = false
`

func (q *Queries) GetStudyByID(ctx context.Context, id uuid.UUID) (Study, error) {
	row := q.queryRow(ctx, q.getStudyByIDStmt, getStudyByID, id)
	var i Study
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudyID,
		&i.Patient,
		&i.Age,
		&i.Department,
		&i.NameOperation,
		&i.StudyType,
		&i.DescrOperation,
		&i.TimeBeginning,
		&i.TimeDuration,
		&i.Surgeon,
		&i.DicomLink,
		&i.Deleted,
	)
	return i, err
}

const getStudyByPatient = `-- name: GetStudyByPatient :one
SELECT id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted FROM studies
WHERE patient = $1 AND deleted = false
`

func (q *Queries) GetStudyByPatient(ctx context.Context, patient string) (Study, error) {
	row := q.queryRow(ctx, q.getStudyByPatientStmt, getStudyByPatient, patient)
	var i Study
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudyID,
		&i.Patient,
		&i.Age,
		&i.Department,
		&i.NameOperation,
		&i.StudyType,
		&i.DescrOperation,
		&i.TimeBeginning,
		&i.TimeDuration,
		&i.Surgeon,
		&i.DicomLink,
		&i.Deleted,
	)
	return i, err
}

const softDeleteAllStudies = `-- name: SoftDeleteAllStudies :exec
UPDATE studies SET deleted = true, updated_at = NOW()
WHERE deleted = false
`

func (q *Queries) SoftDeleteAllStudies(ctx context.Context) error {
	_, err := q.exec(ctx, q.softDeleteAllStudiesStmt, softDeleteAllStudies)
	return err
}

const softDeleteStudy = `-- name: SoftDeleteStudy :exec
UPDATE studies SET deleted = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteStudy(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.softDeleteStudyStmt, softDeleteStudy, id)
	return err
}

const updateStudyDicomLink = `-- name: UpdateStudyDicomLink :one
UPDATE studies
SET dicom_link = $2, updated_at = NOW()
WHERE id = $1 AND deleted = false
RETURNING id, created_at, updated_at, study_id, patient, age, department, name_operation, study_type, descr_operation, time_beginning, time_duration, surgeon, dicom_link, deleted
`

type UpdateStudyDicomLinkParams struct {
	ID        uuid.UUID      `json:"id"`
	DicomLink sql.NullString `json:"dicom_link"`
}

func (q *Queries) UpdateStudyDicomLink(ctx context.Context, arg UpdateStudyDicomLinkParams) (Study, error) {
	row := q.queryRow(ctx, q.updateStudyDicomLinkStmt, updateStudyDicomLink, arg.ID, arg.DicomLink)
	var i Study
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudyID,
		&i.Patient,
		&i.Age,
		&i.Department,
		&i.NameOperation,
		&i.StudyType,
		&i.DescrOperation,
		&i.TimeBeginning,
		&i.TimeDuration,
		&i.Surgeon,
		&i.DicomLink,
		&i.Deleted,
	)
	return i, err
}
