// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_requests.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const claimNextUserRequest = `-- name: ClaimNextUserRequest :one
WITH next_request AS (
    SELECT id
    FROM user_requests
    WHERE user_requests.agent_id = $1
      AND user_requests.attempt_count < user_requests.max_attempts
      AND (
          (status = 'pending' AND available_at <= NOW())
          OR (status = 'in_progress' AND lease_expires_at <= NOW())
      )
    ORDER BY available_at ASC, created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE user_requests AS request
SET status = 'in_progress',
    attempt_count = request.attempt_count + 1,
    updated_at = NOW(),
    lease_expires_at = NOW() + INTERVAL '5 minutes'
FROM next_request
WHERE request.id = next_request.id
RETURNING request.id, request.created_at, request.updated_at, request.available_at, request.lease_expires_at, request.completed_at, request.status, request.user_id, request.agent_id, request.request_type, request.command, request.payload, request.result, request.error_log, request.attempt_count, request.max_attempts
`

func (q *Queries) ClaimNextUserRequest(ctx context.Context, agentID int32) (UserRequest, error) {
	row := q.queryRow(ctx, q.claimNextUserRequestStmt, claimNextUserRequest, agentID)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const completeUserRequest = `-- name: CompleteUserRequest :one
UPDATE user_requests
SET status = 'completed',
    result = $3,
    error_log = NULL,
    updated_at = NOW(),
    completed_at = NOW(),
    lease_expires_at = NULL
WHERE id = $1
  AND agent_id = $2
  AND status = 'in_progress'
RETURNING id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
`

type CompleteUserRequestParams struct {
	ID      uuid.UUID       `json:"id"`
	AgentID int32           `json:"agent_id"`
	Result  json.RawMessage `json:"result"`
}

func (q *Queries) CompleteUserRequest(ctx context.Context, arg CompleteUserRequestParams) (UserRequest, error) {
	row := q.queryRow(ctx, q.completeUserRequestStmt, completeUserRequest, arg.ID, arg.AgentID, arg.Result)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const createUserRequest = `-- name: CreateUserRequest :one
INSERT INTO user_requests (
    user_id,
    agent_id,
    request_type,
    command,
    payload,
    max_attempts
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
`

type CreateUserRequestParams struct {
	UserID      string          `json:"user_id"`
	AgentID     int32           `json:"agent_id"`
	RequestType string          `json:"request_type"`
	Command     string          `json:"command"`
	Payload     json.RawMessage `json:"payload"`
	MaxAttempts int32           `json:"max_attempts"`
}

func (q *Queries) CreateUserRequest(ctx context.Context, arg CreateUserRequestParams) (UserRequest, error) {
	row := q.queryRow(ctx, q.createUserRequestStmt, createUserRequest,
		arg.UserID,
		arg.AgentID,
		arg.RequestType,
		arg.Command,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const deleteAllUserRequests = `-- name: DeleteAllUserRequests :execrows
DELETE FROM user_requests
WHERE user_id = $1 AND agent_id = $2
`

type DeleteAllUserRequestsParams struct {
	UserID  string `json:"user_id"`
	AgentID int32  `json:"agent_id"`
}

func (q *Queries) DeleteAllUserRequests(ctx context.Context, arg DeleteAllUserRequestsParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteAllUserRequestsStmt, deleteAllUserRequests, arg.UserID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldRequests = `-- name: DeleteOldRequests :exec
DELETE FROM user_requests
WHERE status IN ('completed', 'error')
  AND completed_at < NOW() - INTERVAL '3 days'
`

func (q *Queries) DeleteOldRequests(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteOldRequestsStmt, deleteOldRequests)
	return err
}

const deleteUserRequest = `-- name: DeleteUserRequest :execrows
DELETE FROM user_requests
WHERE id = $1 AND user_id = $2
`

type DeleteUserRequestParams struct {
	ID     uuid.UUID `json:"id"`
	UserID string    `json:"user_id"`
}

func (q *Queries) DeleteUserRequest(ctx context.Context, arg DeleteUserRequestParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserRequestStmt, deleteUserRequest, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failUserRequest = `-- name: FailUserRequest :one
UPDATE user_requests
SET status = 'error',
    error_log = $3,
    updated_at = NOW(),
    completed_at = NOW(),
    lease_expires_at = NULL
WHERE id = $1
  AND agent_id = $2
  AND status = 'in_progress'
RETURNING id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
`

type FailUserRequestParams struct {
	ID       uuid.UUID      `json:"id"`
	AgentID  int32          `json:"agent_id"`
	ErrorLog sql.NullString `json:"error_log"`
}

func (q *Queries) FailUserRequest(ctx context.Context, arg FailUserRequestParams) (UserRequest, error) {
	row := q.queryRow(ctx, q.failUserRequestStmt, failUserRequest, arg.ID, arg.AgentID, arg.ErrorLog)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const getOldRequestsForArchive = `-- name: GetOldRequestsForArchive :many
SELECT id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
FROM user_requests
WHERE status IN ('completed', 'error')
  AND completed_at < NOW() - INTERVAL '3 days'
ORDER BY completed_at ASC
`

func (q *Queries) GetOldRequestsForArchive(ctx context.Context) ([]UserRequest, error) {
	rows, err := q.query(ctx, q.getOldRequestsForArchiveStmt, getOldRequestsForArchive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRequest
	for rows.Next() {
		var i UserRequest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.LeaseExpiresAt,
			&i.CompletedAt,
			&i.Status,
			&i.UserID,
			&i.AgentID,
			&i.RequestType,
			&i.Command,
			&i.Payload,
			&i.Result,
			&i.ErrorLog,
			&i.AttemptCount,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRequestByID = `-- name: GetUserRequestByID :one
SELECT id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
FROM user_requests
WHERE id = $1
`

func (q *Queries) GetUserRequestByID(ctx context.Context, id uuid.UUID) (UserRequest, error) {
	row := q.queryRow(ctx, q.getUserRequestByIDStmt, getUserRequestByID, id)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}

const listUserRequests = `-- name: ListUserRequests :many
SELECT id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
FROM user_requests
WHERE user_id = $1 AND agent_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListUserRequestsParams struct {
	UserID  string `json:"user_id"`
	AgentID int32  `json:"agent_id"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListUserRequests(ctx context.Context, arg ListUserRequestsParams) ([]UserRequest, error) {
	rows, err := q.query(ctx, q.listUserRequestsStmt, listUserRequests, arg.UserID, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRequest
	for rows.Next() {
		var i UserRequest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvailableAt,
			&i.LeaseExpiresAt,
			&i.CompletedAt,
			&i.Status,
			&i.UserID,
			&i.AgentID,
			&i.RequestType,
			&i.Command,
			&i.Payload,
			&i.Result,
			&i.ErrorLog,
			&i.AttemptCount,
			&i.MaxAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryUserRequest = `-- name: RetryUserRequest :one
UPDATE user_requests
SET status = CASE
        WHEN attempt_count < max_attempts THEN 'pending'
        ELSE 'error'
    END,
    error_log = $3,
    updated_at = NOW(),
    available_at = NOW() + INTERVAL '30 seconds',
    lease_expires_at = NULL,
    completed_at = CASE
        WHEN attempt_count < max_attempts THEN NULL
        ELSE NOW()
    END
WHERE id = $1
  AND agent_id = $2
  AND status = 'in_progress'
RETURNING id, created_at, updated_at, available_at, lease_expires_at, completed_at, status, user_id, agent_id, request_type, command, payload, result, error_log, attempt_count, max_attempts
`

type RetryUserRequestParams struct {
	ID       uuid.UUID      `json:"id"`
	AgentID  int32          `json:"agent_id"`
	ErrorLog sql.NullString `json:"error_log"`
}

func (q *Queries) RetryUserRequest(ctx context.Context, arg RetryUserRequestParams) (UserRequest, error) {
	row := q.queryRow(ctx, q.retryUserRequestStmt, retryUserRequest, arg.ID, arg.AgentID, arg.ErrorLog)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvailableAt,
		&i.LeaseExpiresAt,
		&i.CompletedAt,
		&i.Status,
		&i.UserID,
		&i.AgentID,
		&i.RequestType,
		&i.Command,
		&i.Payload,
		&i.Result,
		&i.ErrorLog,
		&i.AttemptCount,
		&i.MaxAttempts,
	)
	return i, err
}
