// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_requests.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const completeUserRequest = `-- name: CompleteUserRequest :one
UPDATE user_requests
SET 
    status = 'completed',
    updated_at = NOW()
WHERE id = $1 AND status = 'in_process'
RETURNING id, created_at, updated_at, status, user_id, request_type, command, study_id, xa_id, ct_id, study_filter, xa_filter, ct_filter, error_log
`

func (q *Queries) CompleteUserRequest(ctx context.Context, id uuid.UUID) (UserRequest, error) {
	row := q.queryRow(ctx, q.completeUserRequestStmt, completeUserRequest, id)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.UserID,
		&i.RequestType,
		&i.Command,
		&i.StudyID,
		&i.XaID,
		&i.CtID,
		&i.StudyFilter,
		&i.XaFilter,
		&i.CtFilter,
		&i.ErrorLog,
	)
	return i, err
}

const createUserRequest = `-- name: CreateUserRequest :one
INSERT INTO user_requests (
    status, user_id, request_type, command, 
    study_id, xa_id, ct_id, 
    study_filter, xa_filter, ct_filter,
    error_log
)
VALUES (
    'pending', $1, $2, $3, 
    $4, $5, $6, 
    $7, $8, $9,
    NULL
)
RETURNING id
`

type CreateUserRequestParams struct {
	UserID      string         `json:"user_id"`
	RequestType string         `json:"request_type"`
	Command     sql.NullString `json:"command"`
	StudyID     sql.NullString `json:"study_id"`
	XaID        sql.NullString `json:"xa_id"`
	CtID        sql.NullString `json:"ct_id"`
	StudyFilter sql.NullString `json:"study_filter"`
	XaFilter    sql.NullString `json:"xa_filter"`
	CtFilter    sql.NullString `json:"ct_filter"`
}

func (q *Queries) CreateUserRequest(ctx context.Context, arg CreateUserRequestParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.createUserRequestStmt, createUserRequest,
		arg.UserID,
		arg.RequestType,
		arg.Command,
		arg.StudyID,
		arg.XaID,
		arg.CtID,
		arg.StudyFilter,
		arg.XaFilter,
		arg.CtFilter,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteOldRequests = `-- name: DeleteOldRequests :exec
DELETE FROM user_requests
WHERE status IN ('completed', 'failed')
  AND updated_at < NOW() - INTERVAL '3 days'
`

func (q *Queries) DeleteOldRequests(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteOldRequestsStmt, deleteOldRequests)
	return err
}

const failUserRequest = `-- name: FailUserRequest :one
UPDATE user_requests
SET 
    status = 'failed',
    updated_at = NOW(),
    error_log = $2
WHERE id = $1 AND status = 'in_process'
RETURNING id, created_at, updated_at, status, user_id, request_type, command, study_id, xa_id, ct_id, study_filter, xa_filter, ct_filter, error_log
`

type FailUserRequestParams struct {
	ID       uuid.UUID      `json:"id"`
	ErrorLog sql.NullString `json:"error_log"`
}

func (q *Queries) FailUserRequest(ctx context.Context, arg FailUserRequestParams) (UserRequest, error) {
	row := q.queryRow(ctx, q.failUserRequestStmt, failUserRequest, arg.ID, arg.ErrorLog)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.UserID,
		&i.RequestType,
		&i.Command,
		&i.StudyID,
		&i.XaID,
		&i.CtID,
		&i.StudyFilter,
		&i.XaFilter,
		&i.CtFilter,
		&i.ErrorLog,
	)
	return i, err
}

const getAndProcessNextUserRequest = `-- name: GetAndProcessNextUserRequest :one
UPDATE user_requests
SET 
    status = 'in_process',
    updated_at = NOW()
WHERE id = (
    SELECT id 
    FROM user_requests 
    WHERE 
        status = 'pending'
        OR (
            status = 'in_process' 
            AND updated_at < NOW() - CASE 
                WHEN request_type IN ('find_study', 'find_xa', 'find_ct', 'execute_command') THEN INTERVAL '5 minutes'
                WHEN request_type IN ('get_xa', 'get_ct') THEN INTERVAL '15 minutes'
                ELSE INTERVAL '30 minutes' -- Дефолтный таймаут на случай появления новых типов
            END
        )
    ORDER BY created_at ASC 
    LIMIT 1
)
RETURNING id, created_at, updated_at, status, user_id, request_type, command, study_id, xa_id, ct_id, study_filter, xa_filter, ct_filter, error_log
`

func (q *Queries) GetAndProcessNextUserRequest(ctx context.Context) (UserRequest, error) {
	row := q.queryRow(ctx, q.getAndProcessNextUserRequestStmt, getAndProcessNextUserRequest)
	var i UserRequest
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.UserID,
		&i.RequestType,
		&i.Command,
		&i.StudyID,
		&i.XaID,
		&i.CtID,
		&i.StudyFilter,
		&i.XaFilter,
		&i.CtFilter,
		&i.ErrorLog,
	)
	return i, err
}

const getOldRequestsForArchive = `-- name: GetOldRequestsForArchive :many
SELECT id, created_at, updated_at, status, user_id, request_type, command, study_id, xa_id, ct_id, study_filter, xa_filter, ct_filter, error_log 
FROM user_requests
WHERE status IN ('completed', 'failed')
  AND updated_at < NOW() - INTERVAL '3 days'
ORDER BY updated_at ASC
`

func (q *Queries) GetOldRequestsForArchive(ctx context.Context) ([]UserRequest, error) {
	rows, err := q.query(ctx, q.getOldRequestsForArchiveStmt, getOldRequestsForArchive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRequest
	for rows.Next() {
		var i UserRequest
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.UserID,
			&i.RequestType,
			&i.Command,
			&i.StudyID,
			&i.XaID,
			&i.CtID,
			&i.StudyFilter,
			&i.XaFilter,
			&i.CtFilter,
			&i.ErrorLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
